1:
  name: Einfach
  dauer: 10
  leistungen:
  - id: 1
    schema: [0,1,2,3,4,5,6]
  - id: 17
    schema: [0,1,2,3,4,5,6]
  - id: 30
    anzahl: 1
  - id: 20
    schema: [0,1,2,3,4,5,6]
2:
  name: Umfangreich
  dauer: 15
  leistungen:
  - id: 1
    schema: [1,2,3,4,5,6]
  - id: 17
    schema: [0,1,2,3,4,5,6]
  - id: 2
    schema: [0]
  - id: 30
    anzahl: 1
  - id: 20
    schema: [0,1,2,3,4,5,6]
3:
  name: Kompliziert
  dauer: 20
  leistungen:
  - id: 2
    schema: [1,3]
  - id: 17
    schema: [1,3]
  - id: 20
    schema: [1,3]
  - id: 50
    anzahl: 90 
4:
  name: Viele HPEs
  dauer: 30
  leistungen:
  - id: 46
    schema: [0,1,2,3,4,5,6]
  - id: 47
    schema: [0,1,2,3,4,5,6]
  - id: 20
    schema: [0,1,2,3,4,5,6]
5:
  name: Pflegegrad 1
  dauer: 4
  leistungen:
  - id: 1
    schema: [1,3,5,6]
  - id: 2
    schema: [0,2,4]
  - id: 20
    schema: [0,1,2,3,4,5,6]
