Aaron
Abdul
Abdullah
Adam
Adrian
Adriano
Ahmad
Ahmed
Ahmet
Albert
Alessio
Alex
Alexander
Alfred
Ali
Amir
Amon
Andre
Andreas
Angelo
Ansgar
Anton
Antonio
Arian
Armin
Arne
Arno
Arthur
Artur
Arved
Arvid
Ayman
Bastian
Bela
Benedikt
Benjamin
Bennett
Benno
Bernd
Bilal
Bjarne
Björn
Boris
Bruno
Calvin
Can
Carl
Carsten
Caspar
Cedrik
Cem
Chris
Christian
Christoph
Claas
Clemens
Constantin
Curt
Damian
Damien
Daniel
Danilo
Danny
Dario
Darius
David
Davin
Deniz
Dennis
Domenic
Domenik
Dominic
Dominik
Dorian
Dustin
Eddy
Edgar
Edwin
Elias
Emanuel
Emil
Emilian
Emirhan
Emre
Enes
Enno
Enrico
Erik
Erwin
Fabian
Fabien
Fabio
Fabrice
Falk
Felix
Ferdinand
Fiete
Finn
Florian
Francesco
Franz
Frederick
Frederik
Friedrich
Fritz
Furkan
Gabriel
Georg
Gianluca
Gino
Giuliano
Giuseppe
Gregor
Gustav
Hagen
Hanno
Hans
Hasan
Hassan
Hauke
Hendrik
Hennes
Henning
Henrick
Henrik
Henry
Hermann
Herbert
Heribert
Heinz
Hanspeter
Hans-Jürgen
Hugo
Hussein
Ibrahim
Ilias
Immanuel
Ismael
Ivan
Jacob
Jakob
Jamal
Jan
Jannik
Janosch
Jarne
Jason
Jasper
Jens
Jeremias
Jerome
Jesper
Jesse
Joel
Johann
Johannes
John
Johnny
Jona
Jonah
Jonas
Jonathan
Joost
Jordan
Joschua
Josef
Joseph
Joshua
Josua
Julian
Julien
Julius
Juri
Justin
Justus
Kaan
Kai
Kalle
Kami
Karim
Karl
Karl-Heinz
Keno
Kerem
Kevin
Kilian
Klaas
Klaus
Klemens
Konrad
Konstantin
Kurt
Kurt-Georg
Lars
Laurens
Laurenz
Laurin
Leander
Leif
Leo
Leon
Leonard
Leonardo
Leonhard
Leopold
Levent
Levin
Lewin
Lewis
Linus
Lion
Lionel
Lorenz
Lorenzo
Louis
Lucas
Lucian
Ludwig
Luis
Luiz
Lukas
Magnus
Maik
Maksim
Malte
Manfred
Manuel
Marc
Marcel
Marco
Marcus
Marek
Mario
Marius
Mark
Marko
Markus
Marlon
Marten
Martin
Marvin
Marwin
Mathis
Matis
Mats
Matteo
Mattes
Matthias
Matthis
Maurice
Max
Maxim
Maximilian
Mehmet
Melvin
Merlin
Michael
Michel
Mikail
Mike
Milan
Milo
Mirco
Mirko
Mohamed
Moritz
Morten
Muhammed
Murat
Mustafa
Nathan
Nathanael
Neko
Nick
Nico
Nicolai
Niels
Nikita
Niklas
Niko
Nikolai
Nikolas
Nils
Noah
Norman
Ole
Oliver
Omar
Oscar
Oskar
Pascal
Patrick
Paul
Peer
Peter
Philip
Philipp
Piet
Pit
Quentin
Quirin
Rafael
Ramon
Raphael
Rasmus
Raul
Riccardo
Richard
Rick
Rico
Robert
Robin
Rocco
Roman
Ruben
Rüdiger
Ryan
Salih
Samuel
Sandro
Sascha
Sebastian
Silas
Simeon
Simon
Stefan
Steffen
Stephan
Sven
Sönke
Sören
Tamino
Tarik
Teo
Theo
Theodor
Thilo
Thomas
Thorben
Til
Till
Tillmann
Tim
Timm
Timo
Timon
Tino
Titus
Tizian
Tobias
Tom
Tommy
Toni
Tony
Torben
Tore
Tristan
Udo
Ullrich
Umberto
Uwe
Valentin
Valentino
Veit
Victor
Viktor
Vincent
Vito
Vitus
Waldemar
Wilhelm
Willi
Willibald
Willy
Xaver
Yannic
Yannick
Yannik
Yannis
Yasin
Youssef
Yusuf
Yves
Ömer
Aaliyah
Abigail
Ada
Adelina
Adriana
Aileen
Alana
Alena
Alexa
Alexandra
Alexia
Alexis
Aleyna
Alica
Alice
Alicia
Alina
Alisa
Alisha
Alissa
Allegra
Alma
Alyssa
Amalia
Amanda
Amelia
Amelie
Anabel
Anastasia
Andrea
Angela
Angelina
Angelique
Anja
Ann
Anna
Annabel
Annabell
Annabelle
Annalena
Anne
Anneke
Annelie
Annemarie
Anni
Annie
Annika
Anny
Anouk
Antonia
Ariana
Ariane
Ashley
Asya
Aurelia
Aurora
Beate
Birgit
Brunhilde
Betty
Bianca
Bianka
Brigitte
Carina
Carla
Carlotta
Carmen
Carolin
Carolina
Caroline
Cassandra
Catharina
Catrin
Cecilia
Celia
Celina
Celine
Ceylin
Chantal
Charlotta
Charlotte
Chiara
Christin
Christiane
Christina
Cindy
Claire
Clara
Clarissa
Cora
Cordula
Corinna
Cosima
Dana
Daniela
Darleen
Delia
Denise
Diana
Dina
Dorothea
Eda
Eileen
Elaine
Elea
Elena
Eleni
Eleonora
Eliana
Elisa
Elisabeth
Ella
Ellen
Elli
Elly
Elsa
Emelie
Emilia
Emilie
Emma
Emmi
Esther
Eva
Evelin
Evelina
Eveline
Evelyn
Fabienne
Fatima
Fatma
Felicia
Felicitas
Felina
Finja
Fiona
Flora
Florentine
Francesca
Franka
Franziska
Frederike
Freya
Frida
Frieda
Friederike
Gina
Giulia
Giuliana
Greta
Hana
Hanna
Hannah
Heidi
Helen
Helena
Helene
Henriette
Henrike
Hermine
Ida
Imke
Ina
Ines
Inga
Ingrid
Inka
Isabel
Isabell
Isabella
Isabelle
Ivonne
Jacqueline
Jamie
Jamila
Jana
Jane
Janina
Janine
Janna
Janne
Jasmin
Jasmina
Jasmine
Jenna
Jennifer
Jenny
Jessica
Jessy
Jette
Joanna
Joelina
Joeline
Johanna
Jolina
Joline
Josefin
Josefine
Josephin
Josephine
Judith
Judy
Jule
Julia
Juliana
Juliane
Julie
Julienne
Julika
Julina
Juna
Justine
Kaja
Karina
Karla
Karlotta
Karolina
Karoline
Kassandra
Katarina
Katharina
Kathrin
Katja
Katrin
Kaya
Kayra
Kim
Klara
Korinna
Kristin
Laila
Lana
Lara
Larissa
Laura
Laureen
Lavinia
Lea
Leah
Leana
Leandra
Leila
Lena
Lene
Leni
Lenia
Lenja
Lenya
Leona
Leoni
Leonie
Leonora
Letizia
Lili
Lilian
Liliana
Lilith
Lilli
Lilly
Lily
Lina
Linda
Line
Linnea
Lisa
Lisanne
Livia
Liz
Lola
Loreen
Lorena
Lotta
Lotte
Louisa
Louise
Lucia
Lucie
Lucienne
Lucy
Luisa
Luise
Luzie
Madeleine
Madita
Madlen
Magdalena
Maike
Maja
Malena
Mandy
Marah
Mareike
Maren
Maria
Mariam
Marie
Marieke
Mariella
Marika
Marina
Marisa
Marissa
Marit
Marleen
Marlen
Marlena
Marlene
Marta
Martha
Mary
Maryam
Mathilda
Mathilde
Matilda
Maxi
Maxima
Maxine
Maya
Medina
Meike
Melanie
Melek
Melike
Melina
Melinda
Melis
Melisa
Melissa
Merle
Meryem
Mette
Mia
Michaela
Michelle
Milana
Milena
Mina
Miriam
Mirja
Mona
Monique
Nadine
Nadja
Naomi
Natalia
Natalie
Nathalie
Neele
Nele
Nelli
Nelly
Nicole
Nina
Noemi
Nora
Olivia
Patricia
Patrizia
Paula
Paulina
Pauline
Penelope
Philine
Phoebe
Pia
Rahel
Rania
Rebecca
Rebekka
Riana
Rieke
Rike
Romina
Romy
Ronja
Rosa
Rosalie
Ruby
Sabrina
Sahra
Sally
Salome
Samantha
Sandra
Sandy
Sanja
Saphira
Sara
Sarah
Saskia
Selina
Selma
Sena
Sidney
Sienna
Silja
Sina
Sofia
Sofie
Sonja
Sophia
Sophie
Stefanie
Stella
Stephanie
Stina
Susanne
Svea
Svenja
Sydney
Tabea
Talea
Talia
Tamara
Tamia
Tamina
Tanja
Tara
Tarja
Teresa
Tessa
Thalea
Thalia
Thea
Theresa
Tina
Ursula
Valentina
Valeria
Valerie
Vanessa
Vera
Veronika
Victoria
Viktoria
Viola
Vivian
Vivien
Vivienne
Wibke
Wiebke
Xenia
Yaren
Yasmin
Yvonne
Zara
Zehra
Zoe
Zoé
